# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd0cea05cf731a5f5e76e6c01d2006c5d2e68c16a5138a9f6daed629c22acd04444059fe29529fd6703a53f32074cc575fb94c22046c9c8315676dc95932f5a

test:
  secret_key_base: 135a2504d994816ce6a1951382b487245c118f64a554e0fa2e89c2d6415f714b78c050839371a4fe5b87e5d238d14fe3059111accf63213912e004effa316f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
